server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:vault://
  datasource:
#    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/todos_db}
#    username: ${DATABASE_USERNAME:postgres}
#    password: ${DATABASE_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  cloud:
    vault:
      uri: ${VAULT_ADDR:http://host.docker.internal:8200}
      token: dev-root-token
      kv:
        enabled: true
        backend: kv
        application-name: todos-api

logging:
  level:
    root: ${LOG_LEVEL:info}
    com.example.todos: ${LOG_LEVEL:info}
